{{ config(schema=var('reports')) }}




SELECT CURRENT_TIMESTAMP AS snapshot_timestamp
     ----
     , date
     , BOOKINGS
     , BOOKINGS_LAST_7_DAYS
     , BOOKINGS_LAST_14_DAYS
     , BOOKINGS_QTD
     , BOOKINGS_TRIP_REPEAT
     , BOOKINGS_TRIP_REPEAT_LAST_7_DAYS
     , BOOKINGS_TRIP_REPEAT_LAST_14_DAYS
     , BOOKINGS_TRIP_REPEAT_QTD
     , NR_TRIP_REPEAT
     , NR_TRIP_REPEAT_LAST_7_DAYS
     , NR_TRIP_REPEAT_LAST_14_DAYS
     , NR_TRIP_REPEAT_QTD
     , NR
     , NR_LAST_7_DAYS
     , NR_LAST_14_DAYS
     , NR_QTD
     , NR_PAID_SEARCH
     , NR_PAID_SEARCH_LAST_7_DAYS
     , NR_PAID_SEARCH_LAST_14_DAYS
     , NR_PAID_SEARCH_QTD
     , NR_NON_PAID_CHANNELS
     , NR_NON_PAID_CHANNELS_LAST_7_DAYS
     , NR_NON_PAID_CHANNELS_LAST_14_DAYS
     , NR_NON_PAID_CHANNELS_QTD
     , NR_PERFORMANCE_MARKETING
     , NR_PERFORMANCE_MARKETING_LAST_7_DAYS
     , NR_PERFORMANCE_MARKETING_LAST_14_DAYS
     , NR_PERFORMANCE_MARKETING_QTD
     , NR_STR
     , NR_STR_LAST_7_DAYS
     , NR_STR_LAST_14_DAYS
     , NR_STR_QTD
     , GMV
     , GMV_LAST_7_DAYS
     , GMV_LAST_14_DAYS
     , GMV_QTD
     , ROAS_PERFORMANCE_MARKETING
     , ROAS_PERFORMANCE_MARKETING_LAST_7_DAYS
     , ROAS_PERFORMANCE_MARKETING_LAST_14_DAYS
     , ROAS_PERFORMANCE_MARKETING_QTD
     , ROAS_PAID_SEARCH
     , ROAS_PAID_SEARCH_LAST_7_DAYS
     , ROAS_PAID_SEARCH_LAST_14_DAYS
     , ROAS_PAID_SEARCH_QTD
     , TRANSACTIONS
     , TRANSACTIONS_LAST_7_DAYS
     , TRANSACTIONS_LAST_14_DAYS
     , TRANSACTIONS_QTD
     , GUIDED_TOURS_ORIGINALS_NR_SHARE
     , GUIDED_TOURS_ORIGINALS_NR_SHARE_LAST_7_DAYS
     , GUIDED_TOURS_ORIGINALS_NR_SHARE_LAST_14_DAYS
     , GUIDED_TOURS_ORIGINALS_NR_SHARE_QTD
     , GUIDED_TOURS_ORIGINALS_EXPERIENCE_SHARE
     , GUIDED_TOURS_ORIGINALS_EXPERIENCE_SHARE_LAST_7_DAYS
     , GUIDED_TOURS_ORIGINALS_EXPERIENCE_SHARE_LAST_14_DAYS
     , GUIDED_TOURS_ORIGINALS_EXPERIENCE_SHARE_QTD
     , VISITORS
     , VISITORS_LAST_7_DAYS
     , VISITORS_LAST_14_DAYS
     , VISITORS_QTD
     , QUOTERS
     , QUOTERS_LAST_7_DAYS
     , QUOTERS_LAST_14_DAYS
     , QUOTERS_QTD
     , CUSTOMERS
     , CUSTOMERS_LAST_7_DAYS
     , CUSTOMERS_LAST_14_DAYS
     , CUSTOMERS_QTD
     , nr_app
     , ROAS_REAL_TIME
     , ROAS_REAL_TIME_LAST_7_DAYS
     , ROAS_REAL_TIME_LAST_14_DAYS
     , ROAS_REAL_TIME_QTD
     , CONTRIBUTION_MARGIN_CHECKOUT
     , CONTRIBUTION_MARGIN_CHECKOUT_LAST_7_DAYS
     , CONTRIBUTION_MARGIN_CHECKOUT_LAST_14_DAYS
     , CONTRIBUTION_MARGIN_CHECKOUT_QTD
     , NR_COMPONENTS
     , NR_COMPONENTS_LAST_7_DAYS
     , NR_COMPONENTS_LAST_14_DAYS
     , NR_COMPONENTS_QTD
     , FIXED_AD_SPEND
     , FIXED_AD_SPEND_LAST_7_DAYS
     , FIXED_AD_SPEND_LAST_14_DAYS
     , FIXED_AD_SPEND_QTD
     , contacts_total
     , trip_customers_acq
     , trip_customers_next_trip_acq
     , trip_customers_trip_repeat
     , bookings_last_week
     , bookings_trip_repeat_last_week
     , customers_last_week
     , gmv_last_week
     , nr_last_week
     , nr_paid_search_last_week
     , nr_performance_marketing_last_week
     , nr_str_last_week
     , roas_paid_search_last_week
     , roas_performance_marketing_last_week
     , roas_real_time_last_week
     , quoters_last_week
     , visitors_last_week
     , transactions_last_week
     , guided_tours_originals_nr_share_last_week
     , guided_tours_originals_experience_share_last_week
     , nr_trip_repeat_last_week
     , nr_non_paid_channels_last_week
     , contribution_margin_checkout_last_week
     , nr_components_last_week
     , fixed_ad_spend_last_week
     , fixed_ad_spend_last_7_days_last_week
     , fixed_ad_spend_last_14_days_last_week
     , fixed_ad_spend_qtd_last_week
     , contacts_total_last_week
     , trip_customers_acq_last_week
     , trip_customers_next_trip_acq_last_week
     , trip_customers_trip_repeat_last_week
     , nr_app_last_week
     , bookings_last_year
     , bookings_trip_repeat_last_year
     , customers_last_year
     , gmv_last_year
     , nr_last_year
     , nr_paid_search_last_year
     , nr_performance_marketing_last_year
     , nr_str_last_year
     , roas_paid_search_last_year
     , roas_performance_marketing_last_year
     , roas_real_time_last_year
     , quoters_last_year
     , visitors_last_year
     , transactions_last_year
     , guided_tours_originals_nr_share_last_year
     , guided_tours_originals_experience_share_last_year
     , nr_trip_repeat_last_year
     , nr_non_paid_channels_last_year
     , contribution_margin_checkout_last_year
     , nr_components_last_year
     , bookings_last_7_days_last_year
     , bookings_trip_repeat_last_7_days_last_year
     , customers_last_7_days_last_year
     , gmv_last_7_days_last_year
     , nr_last_7_days_last_year
     , nr_paid_search_last_7_days_last_year
     , nr_performance_marketing_last_7_days_last_year
     , nr_str_last_7_days_last_year
     , roas_paid_search_last_7_days_last_year
     , roas_performance_marketing_last_7_days_last_year
     , roas_real_time_last_7_days_last_year
     , quoters_last_7_days_last_year
     , visitors_last_7_days_last_year
     , transactions_last_7_days_last_year
     , guided_tours_originals_nr_share_last_7_days_last_year
     , guided_tours_originals_experience_share_last_7_days_last_year
     , nr_trip_repeat_last_7_days_last_year
     , nr_non_paid_channels_last_7_days_last_year
     , contribution_margin_checkout_last_7_days_last_year
     , nr_components_last_7_days_last_year
     , bookings_qtd_last_year
     , bookings_trip_repeat_qtd_last_year
     , customers_qtd_last_year
     , gmv_qtd_last_year
     , nr_qtd_last_year
     , nr_paid_search_qtd_last_year
     , nr_performance_marketing_qtd_last_year
     , nr_str_qtd_last_year
     , roas_paid_search_qtd_last_year
     , roas_performance_marketing_qtd_last_year
     , roas_real_time_qtd_last_year
     , quoters_qtd_last_year
     , visitors_qtd_last_year
     , transactions_qtd_last_year
     , guided_tours_originals_nr_share_qtd_last_year
     , guided_tours_originals_experience_share_qtd_last_year
     , nr_trip_repeat_qtd_last_year
     , nr_non_paid_channels_qtd_last_year
     , contribution_margin_checkout_qtd_last_year
     , nr_components_qtd_last_year
     , fixed_ad_spend_last_year
     , fixed_ad_spend_last_7_days_last_year
     , fixed_ad_spend_last_14_days_last_year
     , fixed_ad_spend_qtd_last_year
     , contacts_total_last_year
     , trip_customers_acq_last_year
     , trip_customers_next_trip_acq_last_year
     , trip_customers_trip_repeat_last_year
     , nr_app_last_year
     , bookings_penultimate_year
     , bookings_trip_repeat_penultimate_year
     , customers_penultimate_year
     , gmv_penultimate_year
     , nr_penultimate_year
     , nr_paid_search_penultimate_year
     , nr_performance_marketing_penultimate_year
     , nr_str_penultimate_year
     , roas_paid_search_penultimate_year
     , roas_performance_marketing_penultimate_year
     , roas_real_time_penultimate_year
     , quoters_penultimate_year
     , visitors_penultimate_year
     , transactions_penultimate_year
     , guided_tours_originals_nr_share_penultimate_year
     , guided_tours_originals_experience_share_penultimate_year
     , nr_trip_repeat_penultimate_year
     , nr_non_paid_channels_penultimate_year
     , contribution_margin_checkout_penultimate_year
     , nr_components_penultimate_year
     , bookings_last_7_days_penultimate_year
     , bookings_trip_repeat_last_7_days_penultimate_year
     , customers_last_7_days_penultimate_year
     , gmv_last_7_days_penultimate_year
     , nr_last_7_days_penultimate_year
     , nr_paid_search_last_7_days_penultimate_year
     , nr_performance_marketing_last_7_days_penultimate_year
     , nr_str_last_7_days_penultimate_year
     , roas_paid_search_last_7_days_penultimate_year
     , roas_performance_marketing_last_7_days_penultimate_year
     , roas_real_time_last_7_days_penultimate_year
     , quoters_last_7_days_penultimate_year
     , visitors_last_7_days_penultimate_year
     , transactions_last_7_days_penultimate_year
     , guided_tours_originals_nr_share_last_7_days_penultimate_year
     , guided_tours_originals_experience_share_last_7_days_penultimate_year
     , nr_trip_repeat_last_7_days_penultimate_year
     , nr_non_paid_channels_last_7_days_penultimate_year
     , contribution_margin_checkout_last_7_days_penultimate_year
     , nr_components_last_7_days_penultimate_year
     , bookings_qtd_penultimate_year
     , bookings_trip_repeat_qtd_penultimate_year
     , customers_qtd_penultimate_year
     , gmv_qtd_penultimate_year
     , nr_qtd_penultimate_year
     , nr_paid_search_qtd_penultimate_year
     , nr_performance_marketing_qtd_penultimate_year
     , nr_str_qtd_penultimate_year
     , roas_paid_search_qtd_penultimate_year
     , roas_performance_marketing_qtd_penultimate_year
     , roas_real_time_qtd_penultimate_year
     , quoters_qtd_penultimate_year
     , visitors_qtd_penultimate_year
     , transactions_qtd_penultimate_year
     , guided_tours_originals_nr_share_qtd_penultimate_year
     , guided_tours_originals_experience_share_qtd_penultimate_year
     , nr_trip_repeat_qtd_penultimate_year
     , nr_non_paid_channels_qtd_penultimate_year
     , contribution_margin_checkout_qtd_penultimate_year
     , nr_components_qtd_penultimate_year
     , fixed_ad_spend_penultimate_year
     , fixed_ad_spend_last_7_days_penultimate_year
     , fixed_ad_spend_last_14_days_penultimate_year
     , fixed_ad_spend_qtd_penultimate_year
     , contacts_total_penultimate_year
     , trip_customers_acq_penultimate_year
     , trip_customers_next_trip_acq_penultimate_year
     , trip_customers_trip_repeat_penultimate_year
     , nr_app_penultimate_year
     , bookings_3_years_ago
     , bookings_trip_repeat_3_years_ago
     , customers_3_years_ago
     , gmv_3_years_ago
     , nr_3_years_ago
     , nr_paid_search_3_years_ago
     , nr_performance_marketing_3_years_ago
     , nr_str_3_years_ago
     , roas_paid_search_3_years_ago
     , roas_performance_marketing_3_years_ago
     , roas_real_time_3_years_ago
     , quoters_3_years_ago
     , visitors_3_years_ago
     , transactions_3_years_ago
     , guided_tours_originals_nr_share_3_years_ago
     , guided_tours_originals_experience_share_3_years_ago
     , nr_trip_repeat_3_years_ago
     , nr_non_paid_channels_3_years_ago
     , contribution_margin_checkout_3_years_ago
     , nr_components_3_years_ago
     , bookings_last_7_days_3_years_ago
     , bookings_trip_repeat_last_7_days_3_years_ago
     , customers_last_7_days_3_years_ago
     , gmv_last_7_days_3_years_ago
     , nr_last_7_days_3_years_ago
     , nr_paid_search_last_7_days_3_years_ago
     , nr_performance_marketing_last_7_days_3_years_ago
     , nr_str_last_7_days_3_years_ago
     , roas_paid_search_last_7_days_3_years_ago
     , roas_performance_marketing_last_7_days_3_years_ago
     , roas_real_time_last_7_days_3_years_ago
     , quoters_last_7_days_3_years_ago
     , visitors_last_7_days_3_years_ago
     , transactions_last_7_days_3_years_ago
     , guided_tours_originals_nr_share_last_7_days_3_years_ago
     , guided_tours_originals_experience_share_last_7_days_3_years_ago
     , nr_trip_repeat_last_7_days_3_years_ago
     , nr_non_paid_channels_last_7_days_3_years_ago
     , contribution_margin_checkout_last_7_days_3_years_ago
     , nr_components_last_7_days_3_years_ago
     , bookings_qtd_3_years_ago
     , bookings_trip_repeat_qtd_3_years_ago
     , customers_qtd_3_years_ago
     , gmv_qtd_3_years_ago
     , nr_qtd_3_years_ago
     , nr_paid_search_qtd_3_years_ago
     , nr_performance_marketing_qtd_3_years_ago
     , nr_str_qtd_3_years_ago
     , roas_paid_search_qtd_3_years_ago
     , roas_performance_marketing_qtd_3_years_ago
     , roas_real_time_qtd_3_years_ago
     , quoters_qtd_3_years_ago
     , visitors_qtd_3_years_ago
     , transactions_qtd_3_years_ago
     , guided_tours_originals_nr_share_qtd_3_years_ago
     , guided_tours_originals_experience_share_qtd_3_years_ago
     , nr_trip_repeat_qtd_3_years_ago
     , nr_non_paid_channels_qtd_3_years_ago
     , contribution_margin_checkout_qtd_3_years_ago
     , nr_components_qtd_3_years_ago
     , fixed_ad_spend_3_years_ago
     , fixed_ad_spend_last_7_days_3_years_ago
     , fixed_ad_spend_last_14_days_3_years_ago
     , fixed_ad_spend_qtd_3_years_ago
     , contacts_total_3_years_ago
     , trip_customers_acq_3_years_ago
     , trip_customers_next_trip_acq_3_years_ago
     , trip_customers_trip_repeat_3_years_ago
     , nr_app_3_years_ago
     ----
     , CURRENT_DATE AS snapshot_date -- as last column because we will partition by it
  FROM {{ ref('agg_metrics_global_extended') }}
