{{ config(schema=var('reports')) }}




SELECT CURRENT_TIMESTAMP AS snapshot_timestamp
     ----
     , report_date
     , country_group_source
     , borders
     , channel
     , is_acquisition
     , ad_spend
     , realtime_ad_spend
     , reseller_costs
     , coupon_costs
     , bookings
     , customers
     , gmv
     , nr
     , transactions
     , ad_spend_last_week
     , realtime_ad_spend_last_week
     , reseller_costs_last_week
     , coupon_costs_last_week
     , bookings_last_week
     , customers_last_week
     , gmv_last_week
     , nr_last_week
     , transactions_last_week
     , ad_spend_last_7_days
     , ad_spend_last_14_days
     , realtime_ad_spend_last_7_days
     , realtime_ad_spend_last_14_days
     , reseller_costs_last_7_days
     , reseller_costs_last_14_days
     , coupon_costs_last_7_days
     , coupon_costs_last_14_days
     , bookings_last_7_days
     , bookings_last_14_days
     , customers_last_7_days
     , customers_last_14_days
     , gmv_last_7_days
     , gmv_last_14_days
     , nr_last_7_days
     , nr_last_14_days
     , transactions_last_7_days
     , transactions_last_14_days
     , ad_spend_last_year
     , realtime_ad_spend_last_year
     , reseller_costs_last_year
     , coupon_costs_last_year
     , bookings_last_year
     , customers_last_year
     , gmv_last_year
     , nr_last_year
     , transactions_last_year
     , ad_spend_last_7_days_last_year
     , ad_spend_last_14_days_last_year
     , realtime_ad_spend_last_7_days_last_year
     , realtime_ad_spend_last_14_days_last_year
     , reseller_costs_last_7_days_last_year
     , reseller_costs_last_14_days_last_year
     , coupon_costs_last_7_days_last_year
     , coupon_costs_last_14_days_last_year
     , bookings_last_7_days_last_year
     , bookings_last_14_days_last_year
     , customers_last_7_days_last_year
     , customers_last_14_days_last_year
     , gmv_last_7_days_last_year
     , gmv_last_14_days_last_year
     , nr_last_7_days_last_year
     , nr_last_14_days_last_year
     , transactions_last_7_days_last_year
     , transactions_last_14_days_last_year
     , ad_spend_penultimate_year
     , realtime_ad_spend_penultimate_year
     , reseller_costs_penultimate_year
     , coupon_costs_penultimate_year
     , bookings_penultimate_year
     , customers_penultimate_year
     , gmv_penultimate_year
     , nr_penultimate_year
     , transactions_penultimate_year
     , ad_spend_last_7_days_penultimate_year
     , ad_spend_last_14_days_penultimate_year
     , realtime_ad_spend_last_7_days_penultimate_year
     , realtime_ad_spend_last_14_days_penultimate_year
     , reseller_costs_last_7_days_penultimate_year
     , reseller_costs_last_14_days_penultimate_year
     , coupon_costs_last_7_days_penultimate_year
     , coupon_costs_last_14_days_penultimate_year
     , bookings_last_7_days_penultimate_year
     , bookings_last_14_days_penultimate_year
     , customers_last_7_days_penultimate_year
     , customers_last_14_days_penultimate_year
     , gmv_last_7_days_penultimate_year
     , gmv_last_14_days_penultimate_year
     , nr_last_7_days_penultimate_year
     , nr_last_14_days_penultimate_year
     , transactions_last_7_days_penultimate_year
     , transactions_last_14_days_penultimate_year
     , ad_spend_3_years_ago
     , realtime_ad_spend_3_years_ago
     , reseller_costs_3_years_ago
     , coupon_costs_3_years_ago
     , bookings_3_years_ago
     , customers_3_years_ago
     , gmv_3_years_ago
     , nr_3_years_ago
     , transactions_3_years_ago
     , ad_spend_last_7_days_3_years_ago
     , ad_spend_last_14_days_3_years_ago
     , realtime_ad_spend_last_7_days_3_years_ago
     , realtime_ad_spend_last_14_days_3_years_ago
     , reseller_costs_last_7_days_3_years_ago
     , reseller_costs_last_14_days_3_years_ago
     , coupon_costs_last_7_days_3_years_ago
     , coupon_costs_last_14_days_3_years_ago
     , bookings_last_7_days_3_years_ago
     , bookings_last_14_days_3_years_ago
     , customers_last_7_days_3_years_ago
     , customers_last_14_days_3_years_ago
     , gmv_last_7_days_3_years_ago
     , gmv_last_14_days_3_years_ago
     , nr_last_7_days_3_years_ago
     , nr_last_14_days_3_years_ago
     , transactions_last_7_days_3_years_ago
     , transactions_last_14_days_3_years_ago
     ----
     , CURRENT_DATE AS snapshot_date -- as last column because we will partition by it
  FROM {{ ref('agg_metrics_drill_down_3_years') }}
